### ISSUE TITLE
feat: Add script name to PATH to run as command

### ISSUE THREAD

**Issue by roshnet** [Haider8/tmessage#13]
## Current issue

Invoking `tmessage` involves running `python msg.py <args>`.

## :bulb: Feature request

Execution script can be made user-friendly if it becomes:
```sh
$ tmessage --user USERNAME --port PORT --server BROKER
```

## :wrench: Implementation / Logic

Adding the script name to PATH environment variable can allow for usage as required.

## Additional comments
_None_

**Comment by roshnet** [comment]
cc @Haider8 @pnijhara

**Comment by Haider8** [comment]
@roshnet @pnijhara  You have any idea, how can we do this?

**Comment by pangeran-bottor** [comment]
One of common practice would be creating `setup.py` and set the entry point. Check this one for example https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html
I would like to work on this if that's ok @Haider8

**Comment by Haider8** [comment]
Thanks for sharing this idea @pangeran-bottor. Yes, go ahead with this issue :+1:

**Comment by Haider8** [comment]
PR #23 fixes it
