### ISSUE TITLE
Implement feature through which chats can be recorded

### ISSUE THREAD

**Issue by Haider8** [Haider8/tmessage#15]
### My suggestion

*Chats can be recorded or saved in some ```txt``` file as soon as we receive them from the server. It should also show the day and time when the messages are received.*

**Comment by clonex10100** [comment]
I would like to try to work on this for hacktoberfest.

**Comment by Haider8** [comment]
Sure, go ahead @clonex10100 :+1: 

Thank you!

**Comment by Shanmugapriya03** [comment]
@Haider8  Can I take this issue?

**Comment by Haider8** [comment]
@Shanmugapriya03 Sure, go ahead :+1:

**Comment by Haider8** [comment]
fixed by #27
