### ISSUE TITLE
enh: Make message storage optional

### ISSUE THREAD

**Issue by Haider8** [Haider8/tmessage#30]
Right now messages are stored in the `messages` directory in the JSON format. Make this feature optional by implementing one more CLI argument, which can be `--store` (argument will be a boolean).

**Comment by Dansyuqri** [comment]
Hi, I am relatively new to contributions and this repo but I would like to pick this up to improve myself. Could I give it a go?

**Comment by Haider8** [comment]
@Dansyuqri Hello, happy to hear that you are looking forward to contributing to open source :). Sure, you can go ahead with this issue :+1: 

:1st_place_medal: If you like this project, please star this repository to show us your support :1st_place_medal:
