### ISSUE TITLE
Feature-Request: Use database for storing the conversion

### ISSUE THREAD

**Issue by Haider8** [Haider8/tmessage#35]

**Comment by AceFire6** [comment]
Hi @Haider8. I'd like to make a PR for this issue. I just wanted to check, what conversion is the title of the issue referring to? Also, do you have any preference on which database to use?

**Comment by Haider8** [comment]
HI @AceFire6! By conversion I mean to say all the messages send and received by the user. After storing the messages in the database we want to implement paging so that users can see their conversations in the terminal.

As far as the choice of database is concerned it can be anything as long as its SQL based. What if its a SQLite database?

**Comment by AceFire6** [comment]
@Haider8, great! SQLite is what I was thinking too. It's simple and lightweight 👍

Cool. Is this meant to replace storing the messages in the JSON files?

**Comment by Haider8** [comment]
Yes, then we wouldn't need JSON files!
