### ISSUE TITLE
Feature-Request: Text formatting

### ISSUE THREAD

**Issue by Haider8** [Haider8/tmessage#37]
For example
* text formatting for code or 
* text formatting using different colors. 

Suggestions are welcome!

**Comment by csaranbalaji** [comment]
I guess a [solution](https://stackoverflow.com/a/17303428) like this would work fine. The user can give the colour / format in tags and the message in between them.

Example : `<bold> message </bold>` is for bold formatting and `<blue> message </blue>` is for sending the text in blue.

**Comment by csaranbalaji** [comment]
May I proceed with the above solution?

**Comment by Haider8** [comment]
@csaranbalaji Go ahead :+1:
